name: Deploy to SmarterASP.NET

on:
  push:
    branches:
      - main  # o la rama que uses para producción

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Cambia si usas otra versión

    - name: Restore dependencies
      run: dotnet restore ./tickets.api/tickets.api.csproj

    - name: Build
      run: dotnet build ./tickets.api/tickets.api.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./tickets.api/tickets.api.csproj --configuration Release --output publish_output

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./publish/
        server-dir: /  # Asegúrate que sea la ruta correcta en tu servidor
